Add comment to document that the completion handler in any NoMethodError (undefined method `push' for #<HTTPClient:0x00007f938515f250>) 	from /Users/davidkmckinney/.rvm/gems/ruby-2.2.1/gems/httpclient-2.8.3/bin/httpclient:47:in `method_missing' 	from (irb):1:in `run' 	from /Users/davidkmckinney/.rvm/gems/ruby-2.2.1/gems/httpclient-2.8.3/bin/httpclient:65:in `block in run' 	from /Users/davidkmckinney/.rvm/gems/ruby-2.2.1/gems/httpclient-2.8.3/bin/httpclient:64:in `catch' 	from /Users/davidkmckinney/.rvm/gems/ruby-2.2.1/gems/httpclient-2.8.3/bin/httpclient:64:in `run' 	from /Users/davidkmckinney/.rvm/gems/ruby-2.2.1/gems/httpclient-2.8.3/bin/httpclient:77:in `<top (required)>' 	from /usr/local/bin/HTTPClient:23:in `load' 	from /usr/local/bin/HTTPClient:23:in `<main>' implementation can be invoked in any thread. Clients are responsible to dispatch to appropriate threads, if needed.